name: 🏗️ Build and publish to Github Container Registry

on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    name: 🧪 Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.9.0]

    steps:
      - name: ⬇️  Checkout repository
        uses: actions/checkout@v4.1.1
      - name: 🔨 Setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: 📲 Install dependencies
        run: |
          npm install
          npm clean-install
      - name: 📝 Test
        run: npm run test-headless
    

  build-and-push-image:
    name: 🏗️ Build and publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: ⬇️  Checkout repository
        uses: actions/checkout@v4.1.1

      - name: 🔑 Log in to the Container registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 📋 Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=auto
            prefix=
            suffix=

      - name: 🏗️ Build and push Docker image
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: 🏗️ Build and push Docker Staging image
        # Only build main images for Staging
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}-Staging
          labels: ${{ steps.meta.outputs.labels }}-Staging
          file: staging.Dockerfile
